

services: 
  db:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${DBrootpass}
    ports: 
      - "3306:3306"
  kino-app:
    image: oven/bun:latest
    build: ./
    environment:
      DATABASE_URL: "mysql://root:${DBrootpass}@db:3306/movies"
    ports: 
      - "5173:5173"
      - "3000:3000"
    depends_on:
      - db
